n_vars: 6              # channel GANs의 수, 학습시킬 자산의 수
file_name: "indices"       # 입력 데이터 파일
n_epochs: 400            # 학습시킬 epoch 수
batch_size: 256      
n_samples: 1             # 각 channel GANs에 입력할 차원의 수 - 각 자산의 종가만 이용하므로 1
criterion: "BCE"        # 손실 함수의 종류 - {BCE, WGAN-GP}
G_type: "LSTM"           # 생성자 네트워크 선택 - {LSTM, TCN}
D_type: "LSTM"           # 판별자 네트워크 선택 - {LSTM, TCN}
CD_type: "MLP"          # 중앙 판별자 네트워크 선택 - {MLP, TCN}
g_lr: 0.001             # 생성자의 학습률
d_lr: 0.001             # 판별자의 학습률
cd_lr: 0.0001           # 중앙 판별자의 학습률
gamma: 5.0              # 중앙 판별자의 손실 함수의 가중치 - 생성자에게 전달할 자산 간 상관관계 정보의 영향력을 조정함
noise_dim: 2            # 생성자에 입력할 노이즈의 차원 수
n_steps: 128           # 입력 데이터의 시퀀스 길이 - {LSTM:48, TCN:127}
device: cuda
seed: 0
